spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/covid-db
        username: postgres
        password: axell
    jpa:
        database-plateform : org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        show-sql: true
        hibernate.ddl-auto: update 
    liquibase:
        enabled: false
logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG